### ISSUE TITLE
Gantt chart example doesn't render in Firefox

### ISSUE THREAD

**Issue by nathantypanski** [palantir/plottable-website#105]
FF 38.0.5 renders the [Gantt chart example](http://plottablejs.org/examples/gantt/) as follows:

![screen shot 2015-06-24 at 11 19 14 am](https://cloud.githubusercontent.com/assets/1385140/8333872/ebdc6fe6-1a62-11e5-9517-f2e713effd5c.png)

**Comment by dbt** [comment]
FYI it also fails to render on Safari.
