### ISSUE TITLE
Docs shows function names in all uppercase

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable-website#29]
It's really hard to figure out the function name from this title:

![screen shot 2014-09-15 at 8 51 57 pm](https://cloud.githubusercontent.com/assets/1440449/4282286/d46c3ada-3d54-11e4-8e33-502e6a27a7ce.png)

There's the declaration under it, but it's still confusing. From inspection in the console, there's a `text-transform: uppercase` set on that heading.

**Comment by rcchen** [comment]
No longer the case. Closing.
