### ISSUE TITLE
http://plottablejs.org/examples/tooltips/ example tooltip has undefined

### ISSUE THREAD

**Issue by diwu1989** [palantir/plottable-website#85]
![image](https://cloud.githubusercontent.com/assets/380950/6795159/5beb5bf2-d199-11e4-9fb6-0e80d7d6c9d8.png)

![image](https://cloud.githubusercontent.com/assets/380950/6795151/37350dbc-d199-11e4-9899-2a09f7088d04.png)

**Comment by bluong** [comment]
Hello @diwu1989 !

The fix you are suggesting is wrapped up in a pull request and we will process it as soon as we are able to.

Thanks a lot for pointing this out!
